create database webApp;
use webApp;
create table users (id int auto_increment primary key, name varchar(40), password varchar(1024), role varchar(30));
GRANT SELECT, INSERT ON webApp.* TO 'lucas'@'localhost' IDENTIFIED BY 'lucas';
insert into users (name,password,role) values ('admin','admin','admin');
insert into users (name,password,role) values ('daniel','naq3jehkjnawjnekaw3ejwenkw','admin');
insert into users (name,password,role) values ('usuario1','432dcqvhnd32skjqhd3u2hk32h4','client');
insert into users (name,password,role) values ('dany','432dcqvhnd32skjqhd3u2hk32h4',,'client');
insert into users (name,password,role) values ('lucas','432dcqvhnd32skjqhd3u2hk32h4','admin');
insert into users (name,password,role) values ('omar','4d23vtt432vt3frd34dr32rs','client');
insert into users (name,password,role) values ('federico','v3fq4dcwfqcf32d2f5345','client');
insert into users (name,password,role) values ('santiago','432dcqvhnd32skjqhd3u2hk32h4','client');
insert into users (name,password,role) values ('gustavo','ewqewq23vtt432vt3frd34dr32rs','client');
insert into users (name,password,role) values ('usuario1','432dcqvhnd32skjqhd3u2hk32h4','client');
insert into users (name,password,role) values ('daniela','432dcqvhnd32skjqhd3u2hk32h4','client');
insert into users (name,password,role) values ('damian','432dcqvhnd32skjqhd3u2hk32h4','client');
insert into users (name,password,role) values ('usuario1','432dcqvhnd32skjqhd3u2hk32h4','client');
insert into users (name,password,role) values ('rodrigo','r23fc3u65365vht3gf435ttwd3','client');
insert into users (name,password,role) values ('usuarioAlgo','432dcqvhnd32skjqhd3u2hk32h4','client');
insert into users (name,password,role) values ('jose','fda323f23f32ede2e23e23h6467i476','client');